#!/bin/sh
# husky

# Created by Husky v4.3.0 (https://github.com/typicode/husky#readme)
#   At: 5/10/2023, 10:34:46 PM
#   From: /workspaces/ra/staking-dapp/node_modules/husky (undefined)

. "$(dirname "$0")/husky.sh"
